name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.27.1

      - name: Deploy to Github Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /
          webRenderer: canvaskit